# Generated by Django 2.2.10 on 2020-02-24 05:56

import EcommerceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, validators=[EcommerceApp.models.uName_Validator])),
                ('password', models.CharField(max_length=100)),
                ('mobileNo', models.IntegerField()),
                ('emailId', models.EmailField(max_length=100)),
            ],
        ),
    ]
